### PR TITLE
Add StackHPC Dashboards and Alerts

### PR DESCRIPTION
**Pull request by JohnGarbutt**

### CODE REVIEW

**Comment by frosty-geek** [comment]
We've added the plusserver examples to JohnGarbutt/scs-monitoring as StackHPC aswell as plusserver is using the same "upstream"

**Comment by berendt** [comment]
@JohnGarbutt As already discussed, we wanted to use osism/kolla-operations for this and move this to Kolla Upstream after discussion at the PTG in October 2021. Can you please open your PR against osism/kolla-operations so we don't have it redundant?

**Comment by JohnGarbutt** [comment]
@berendt that sounds good, we discussed this in the Monitoring subteam, and couldn't find a repo, so I just put it here.

**Comment by fkr** [comment]
From my understanding this was merged into kolla-operations via https://github.com/osism/kolla-operations/pull/1 - as such, I'll close this PR.

**Pull request closed without merging**
